# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Common.proto',
  package='pb',
  serialized_pb=_b('\n\x0c\x43ommon.proto\x12\x02pb\"C\n\x07Product\x12\x11\n\tProductID\x18\x01 \x01(\r\x12\x14\n\x0c\x43urrentStock\x18\x02 \x01(\x05\x12\x0f\n\x07\x45ndTime\x18\x03 \x01(\r\"K\n\x0cGameRankData\x12\x0e\n\x06UserID\x18\x01 \x01(\r\x12\r\n\x05Value\x18\x02 \x01(\r\x12\x0e\n\x06RoleID\x18\x03 \x01(\r\x12\x0c\n\x04Nick\x18\x04 \x01(\t\"M\n\rRedPacketRain\x12\x17\n\x0fredPacketRainID\x18\x01 \x01(\x05\x12\x10\n\x08serialID\x18\x02 \x01(\x05\x12\x11\n\tproductID\x18\x03 \x01(\x05\"W\n\x0fRedPacketRecord\x12\x0e\n\x06userID\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\x0e\n\x06source\x18\x03 \x01(\r\x12\x12\n\nrecordTime\x18\x04 \x01(\x05\"\xe9\x01\n\rBroadcastData\x12\x0e\n\x06GameID\x18\x01 \x01(\r\x12\x13\n\x0b\x42roadcastID\x18\x02 \x01(\r\x12\x18\n\x10\x42roadcastContent\x18\x03 \x01(\t\x12\x0c\n\x04Nick\x18\x04 \x01(\t\x12\x11\n\tGameMoney\x18\x05 \x01(\r\x12\r\n\x05Ratio\x18\x06 \x01(\r\x12\x11\n\tSceneType\x18\x07 \x01(\r\x12\x12\n\nSceneLevel\x18\x08 \x01(\r\x12\x0f\n\x07\x43ontWin\x18\t \x01(\r\x12\x0e\n\x06ItemID\x18\n \x01(\r\x12\x0f\n\x07MatchID\x18\x0b \x01(\r\x12\x10\n\x08ItemCont\x18\x0c \x01(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PRODUCT = _descriptor.Descriptor(
  name='Product',
  full_name='pb.Product',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ProductID', full_name='pb.Product.ProductID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CurrentStock', full_name='pb.Product.CurrentStock', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EndTime', full_name='pb.Product.EndTime', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=87,
)


_GAMERANKDATA = _descriptor.Descriptor(
  name='GameRankData',
  full_name='pb.GameRankData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserID', full_name='pb.GameRankData.UserID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Value', full_name='pb.GameRankData.Value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RoleID', full_name='pb.GameRankData.RoleID', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Nick', full_name='pb.GameRankData.Nick', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=164,
)


_REDPACKETRAIN = _descriptor.Descriptor(
  name='RedPacketRain',
  full_name='pb.RedPacketRain',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='redPacketRainID', full_name='pb.RedPacketRain.redPacketRainID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serialID', full_name='pb.RedPacketRain.serialID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='productID', full_name='pb.RedPacketRain.productID', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=243,
)


_REDPACKETRECORD = _descriptor.Descriptor(
  name='RedPacketRecord',
  full_name='pb.RedPacketRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userID', full_name='pb.RedPacketRecord.userID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='pb.RedPacketRecord.quantity', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='source', full_name='pb.RedPacketRecord.source', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='recordTime', full_name='pb.RedPacketRecord.recordTime', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=332,
)


_BROADCASTDATA = _descriptor.Descriptor(
  name='BroadcastData',
  full_name='pb.BroadcastData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='GameID', full_name='pb.BroadcastData.GameID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BroadcastID', full_name='pb.BroadcastData.BroadcastID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BroadcastContent', full_name='pb.BroadcastData.BroadcastContent', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Nick', full_name='pb.BroadcastData.Nick', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameMoney', full_name='pb.BroadcastData.GameMoney', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Ratio', full_name='pb.BroadcastData.Ratio', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SceneType', full_name='pb.BroadcastData.SceneType', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SceneLevel', full_name='pb.BroadcastData.SceneLevel', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ContWin', full_name='pb.BroadcastData.ContWin', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ItemID', full_name='pb.BroadcastData.ItemID', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MatchID', full_name='pb.BroadcastData.MatchID', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ItemCont', full_name='pb.BroadcastData.ItemCont', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=335,
  serialized_end=568,
)

DESCRIPTOR.message_types_by_name['Product'] = _PRODUCT
DESCRIPTOR.message_types_by_name['GameRankData'] = _GAMERANKDATA
DESCRIPTOR.message_types_by_name['RedPacketRain'] = _REDPACKETRAIN
DESCRIPTOR.message_types_by_name['RedPacketRecord'] = _REDPACKETRECORD
DESCRIPTOR.message_types_by_name['BroadcastData'] = _BROADCASTDATA

Product = _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), dict(
  DESCRIPTOR = _PRODUCT,
  __module__ = 'Common_pb2'
  # @@protoc_insertion_point(class_scope:pb.Product)
  ))
_sym_db.RegisterMessage(Product)

GameRankData = _reflection.GeneratedProtocolMessageType('GameRankData', (_message.Message,), dict(
  DESCRIPTOR = _GAMERANKDATA,
  __module__ = 'Common_pb2'
  # @@protoc_insertion_point(class_scope:pb.GameRankData)
  ))
_sym_db.RegisterMessage(GameRankData)

RedPacketRain = _reflection.GeneratedProtocolMessageType('RedPacketRain', (_message.Message,), dict(
  DESCRIPTOR = _REDPACKETRAIN,
  __module__ = 'Common_pb2'
  # @@protoc_insertion_point(class_scope:pb.RedPacketRain)
  ))
_sym_db.RegisterMessage(RedPacketRain)

RedPacketRecord = _reflection.GeneratedProtocolMessageType('RedPacketRecord', (_message.Message,), dict(
  DESCRIPTOR = _REDPACKETRECORD,
  __module__ = 'Common_pb2'
  # @@protoc_insertion_point(class_scope:pb.RedPacketRecord)
  ))
_sym_db.RegisterMessage(RedPacketRecord)

BroadcastData = _reflection.GeneratedProtocolMessageType('BroadcastData', (_message.Message,), dict(
  DESCRIPTOR = _BROADCASTDATA,
  __module__ = 'Common_pb2'
  # @@protoc_insertion_point(class_scope:pb.BroadcastData)
  ))
_sym_db.RegisterMessage(BroadcastData)


# @@protoc_insertion_point(module_scope)
