# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CSGM.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GameData_pb2
import Response_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CSGM.proto',
  package='pb',
  serialized_pb=_b('\n\nCSGM.proto\x12\x02pb\x1a\x0eGameData.proto\x1a\x0eResponse.proto\"\xba\x02\n\x06GMData\x12\x1e\n\x08\x42\x61seData\x18\x01 \x01(\x0b\x32\x0c.pb.BaseData\x12\x1e\n\x08\x43oreData\x18\x02 \x01(\x0b\x32\x0c.pb.CoreData\x12 \n\tTrackData\x18\x03 \x01(\x0b\x32\r.pb.TrackData\x12\x1e\n\x08GameCore\x18\x04 \x01(\x0b\x32\x0c.pb.GameCore\x12$\n\x0bGameSummary\x18\x05 \x01(\x0b\x32\x0f.pb.GameSummary\x12 \n\tGameTrack\x18\x06 \x01(\x0b\x32\r.pb.GameTrack\x12&\n\x0cMatchAchieve\x18\x07 \x01(\x0b\x32\x10.pb.MatchAchieve\x12\x1c\n\x07\x42\x61gData\x18\x08 \x01(\x0b\x32\x0b.pb.BagData\x12 \n\tExtraData\x18\t \x01(\x0b\x32\r.pb.ExtraData\"H\n\x0eGetPropertyReq\x12\x0e\n\x06GameID\x18\x01 \x01(\r\x12&\n\x0cPropertyData\x18\x02 \x01(\x0b\x32\x10.pb.PropertyData\"V\n\x0eGetPropertyRes\x12\x1c\n\x07ResBase\x18\x01 \x01(\x0b\x32\x0b.pb.ResBase\x12&\n\x0cPropertyData\x18\x02 \x01(\x0b\x32\x10.pb.PropertyData\"*\n\x0cGMDataNotify\x12\x1a\n\x06GMData\x18\x01 \x01(\x0b\x32\n.pb.GMData\"\xab\x01\n\x17GMTRechargeResultNotify\x12\x0e\n\x06UserID\x18\x01 \x01(\r\x12\x15\n\rTRechargeTime\x18\x02 \x01(\r\x12\x13\n\x0btelephoneID\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\r\x12\x0e\n\x06result\x18\x05 \x01(\r\x12\x16\n\x04mail\x18\x06 \x01(\x0b\x32\x08.pb.Mail\x12\x1c\n\x07ResBase\x18\x07 \x01(\x0b\x32\x0b.pb.ResBase')
  ,
  dependencies=[GameData_pb2.DESCRIPTOR,Response_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GMDATA = _descriptor.Descriptor(
  name='GMData',
  full_name='pb.GMData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='BaseData', full_name='pb.GMData.BaseData', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CoreData', full_name='pb.GMData.CoreData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TrackData', full_name='pb.GMData.TrackData', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameCore', full_name='pb.GMData.GameCore', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameSummary', full_name='pb.GMData.GameSummary', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameTrack', full_name='pb.GMData.GameTrack', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MatchAchieve', full_name='pb.GMData.MatchAchieve', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BagData', full_name='pb.GMData.BagData', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ExtraData', full_name='pb.GMData.ExtraData', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=365,
)


_GETPROPERTYREQ = _descriptor.Descriptor(
  name='GetPropertyReq',
  full_name='pb.GetPropertyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='GameID', full_name='pb.GetPropertyReq.GameID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PropertyData', full_name='pb.GetPropertyReq.PropertyData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=439,
)


_GETPROPERTYRES = _descriptor.Descriptor(
  name='GetPropertyRes',
  full_name='pb.GetPropertyRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResBase', full_name='pb.GetPropertyRes.ResBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PropertyData', full_name='pb.GetPropertyRes.PropertyData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=527,
)


_GMDATANOTIFY = _descriptor.Descriptor(
  name='GMDataNotify',
  full_name='pb.GMDataNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='GMData', full_name='pb.GMDataNotify.GMData', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=529,
  serialized_end=571,
)


_GMTRECHARGERESULTNOTIFY = _descriptor.Descriptor(
  name='GMTRechargeResultNotify',
  full_name='pb.GMTRechargeResultNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserID', full_name='pb.GMTRechargeResultNotify.UserID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TRechargeTime', full_name='pb.GMTRechargeResultNotify.TRechargeTime', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='telephoneID', full_name='pb.GMTRechargeResultNotify.telephoneID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='pb.GMTRechargeResultNotify.amount', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='pb.GMTRechargeResultNotify.result', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mail', full_name='pb.GMTRechargeResultNotify.mail', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ResBase', full_name='pb.GMTRechargeResultNotify.ResBase', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=574,
  serialized_end=745,
)

_GMDATA.fields_by_name['BaseData'].message_type = GameData_pb2._BASEDATA
_GMDATA.fields_by_name['CoreData'].message_type = GameData_pb2._COREDATA
_GMDATA.fields_by_name['TrackData'].message_type = GameData_pb2._TRACKDATA
_GMDATA.fields_by_name['GameCore'].message_type = GameData_pb2._GAMECORE
_GMDATA.fields_by_name['GameSummary'].message_type = GameData_pb2._GAMESUMMARY
_GMDATA.fields_by_name['GameTrack'].message_type = GameData_pb2._GAMETRACK
_GMDATA.fields_by_name['MatchAchieve'].message_type = GameData_pb2._MATCHACHIEVE
_GMDATA.fields_by_name['BagData'].message_type = GameData_pb2._BAGDATA
_GMDATA.fields_by_name['ExtraData'].message_type = GameData_pb2._EXTRADATA
_GETPROPERTYREQ.fields_by_name['PropertyData'].message_type = GameData_pb2._PROPERTYDATA
_GETPROPERTYRES.fields_by_name['ResBase'].message_type = Response_pb2._RESBASE
_GETPROPERTYRES.fields_by_name['PropertyData'].message_type = GameData_pb2._PROPERTYDATA
_GMDATANOTIFY.fields_by_name['GMData'].message_type = _GMDATA
_GMTRECHARGERESULTNOTIFY.fields_by_name['mail'].message_type = GameData_pb2._MAIL
_GMTRECHARGERESULTNOTIFY.fields_by_name['ResBase'].message_type = Response_pb2._RESBASE
DESCRIPTOR.message_types_by_name['GMData'] = _GMDATA
DESCRIPTOR.message_types_by_name['GetPropertyReq'] = _GETPROPERTYREQ
DESCRIPTOR.message_types_by_name['GetPropertyRes'] = _GETPROPERTYRES
DESCRIPTOR.message_types_by_name['GMDataNotify'] = _GMDATANOTIFY
DESCRIPTOR.message_types_by_name['GMTRechargeResultNotify'] = _GMTRECHARGERESULTNOTIFY

GMData = _reflection.GeneratedProtocolMessageType('GMData', (_message.Message,), dict(
  DESCRIPTOR = _GMDATA,
  __module__ = 'CSGM_pb2'
  # @@protoc_insertion_point(class_scope:pb.GMData)
  ))
_sym_db.RegisterMessage(GMData)

GetPropertyReq = _reflection.GeneratedProtocolMessageType('GetPropertyReq', (_message.Message,), dict(
  DESCRIPTOR = _GETPROPERTYREQ,
  __module__ = 'CSGM_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetPropertyReq)
  ))
_sym_db.RegisterMessage(GetPropertyReq)

GetPropertyRes = _reflection.GeneratedProtocolMessageType('GetPropertyRes', (_message.Message,), dict(
  DESCRIPTOR = _GETPROPERTYRES,
  __module__ = 'CSGM_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetPropertyRes)
  ))
_sym_db.RegisterMessage(GetPropertyRes)

GMDataNotify = _reflection.GeneratedProtocolMessageType('GMDataNotify', (_message.Message,), dict(
  DESCRIPTOR = _GMDATANOTIFY,
  __module__ = 'CSGM_pb2'
  # @@protoc_insertion_point(class_scope:pb.GMDataNotify)
  ))
_sym_db.RegisterMessage(GMDataNotify)

GMTRechargeResultNotify = _reflection.GeneratedProtocolMessageType('GMTRechargeResultNotify', (_message.Message,), dict(
  DESCRIPTOR = _GMTRECHARGERESULTNOTIFY,
  __module__ = 'CSGM_pb2'
  # @@protoc_insertion_point(class_scope:pb.GMTRechargeResultNotify)
  ))
_sym_db.RegisterMessage(GMTRechargeResultNotify)


# @@protoc_insertion_point(module_scope)
