# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CSNotify.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import GameData_pb2
import Common_pb2
import CSCommon_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CSNotify.proto',
  package='pb',
  serialized_pb=_b('\n\x0e\x43SNotify.proto\x12\x02pb\x1a\x0eGameData.proto\x1a\x0c\x43ommon.proto\x1a\x0e\x43SCommon.proto\"Q\n\x0bTrackNotify\x12 \n\tTrackData\x18\x01 \x01(\x0b\x32\r.pb.TrackData\x12 \n\tGameTrack\x18\x02 \x01(\x0b\x32\r.pb.GameTrack\"$\n\x0fGameEventNotify\x12\x11\n\tEventType\x18\x01 \x01(\r\"0\n\x0eGameStatNotify\x12\x1e\n\x08GameStat\x18\x01 \x01(\x0b\x32\x0c.pb.GameStat\";\n\x0f\x42roadcastNotify\x12(\n\rBroadcastData\x18\x01 \x01(\x0b\x32\x11.pb.BroadcastData\"i\n\x13PlayerLevelUpNotify\x12*\n\x0eOnlineGameData\x18\x01 \x01(\x0b\x32\x12.pb.OnlineGameData\x12&\n\x0cPropertyList\x18\x02 \x03(\x0b\x32\x10.pb.PropertyData\"J\n\x13\x44\x61ilyFirstPayNotify\x12\x10\n\x08PayCount\x18\x01 \x01(\r\x12\x12\n\nMoneyCount\x18\x02 \x01(\r\x12\r\n\x05\x42oxID\x18\x03 \x01(\r\"W\n\x1b\x41\x64\x64itionalPaymentDataNotify\x12\x38\n\x15\x41\x64\x64itionalPaymentData\x18\x01 \x01(\x0b\x32\x19.pb.AdditionalPaymentData')
  ,
  dependencies=[GameData_pb2.DESCRIPTOR,Common_pb2.DESCRIPTOR,CSCommon_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRACKNOTIFY = _descriptor.Descriptor(
  name='TrackNotify',
  full_name='pb.TrackNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='TrackData', full_name='pb.TrackNotify.TrackData', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameTrack', full_name='pb.TrackNotify.GameTrack', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=149,
)


_GAMEEVENTNOTIFY = _descriptor.Descriptor(
  name='GameEventNotify',
  full_name='pb.GameEventNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='EventType', full_name='pb.GameEventNotify.EventType', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=187,
)


_GAMESTATNOTIFY = _descriptor.Descriptor(
  name='GameStatNotify',
  full_name='pb.GameStatNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='GameStat', full_name='pb.GameStatNotify.GameStat', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=237,
)


_BROADCASTNOTIFY = _descriptor.Descriptor(
  name='BroadcastNotify',
  full_name='pb.BroadcastNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='BroadcastData', full_name='pb.BroadcastNotify.BroadcastData', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=298,
)


_PLAYERLEVELUPNOTIFY = _descriptor.Descriptor(
  name='PlayerLevelUpNotify',
  full_name='pb.PlayerLevelUpNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='OnlineGameData', full_name='pb.PlayerLevelUpNotify.OnlineGameData', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PropertyList', full_name='pb.PlayerLevelUpNotify.PropertyList', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=300,
  serialized_end=405,
)


_DAILYFIRSTPAYNOTIFY = _descriptor.Descriptor(
  name='DailyFirstPayNotify',
  full_name='pb.DailyFirstPayNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PayCount', full_name='pb.DailyFirstPayNotify.PayCount', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MoneyCount', full_name='pb.DailyFirstPayNotify.MoneyCount', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BoxID', full_name='pb.DailyFirstPayNotify.BoxID', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=481,
)


_ADDITIONALPAYMENTDATANOTIFY = _descriptor.Descriptor(
  name='AdditionalPaymentDataNotify',
  full_name='pb.AdditionalPaymentDataNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AdditionalPaymentData', full_name='pb.AdditionalPaymentDataNotify.AdditionalPaymentData', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=570,
)

_TRACKNOTIFY.fields_by_name['TrackData'].message_type = GameData_pb2._TRACKDATA
_TRACKNOTIFY.fields_by_name['GameTrack'].message_type = GameData_pb2._GAMETRACK
_GAMESTATNOTIFY.fields_by_name['GameStat'].message_type = GameData_pb2._GAMESTAT
_BROADCASTNOTIFY.fields_by_name['BroadcastData'].message_type = Common_pb2._BROADCASTDATA
_PLAYERLEVELUPNOTIFY.fields_by_name['OnlineGameData'].message_type = CSCommon_pb2._ONLINEGAMEDATA
_PLAYERLEVELUPNOTIFY.fields_by_name['PropertyList'].message_type = GameData_pb2._PROPERTYDATA
_ADDITIONALPAYMENTDATANOTIFY.fields_by_name['AdditionalPaymentData'].message_type = GameData_pb2._ADDITIONALPAYMENTDATA
DESCRIPTOR.message_types_by_name['TrackNotify'] = _TRACKNOTIFY
DESCRIPTOR.message_types_by_name['GameEventNotify'] = _GAMEEVENTNOTIFY
DESCRIPTOR.message_types_by_name['GameStatNotify'] = _GAMESTATNOTIFY
DESCRIPTOR.message_types_by_name['BroadcastNotify'] = _BROADCASTNOTIFY
DESCRIPTOR.message_types_by_name['PlayerLevelUpNotify'] = _PLAYERLEVELUPNOTIFY
DESCRIPTOR.message_types_by_name['DailyFirstPayNotify'] = _DAILYFIRSTPAYNOTIFY
DESCRIPTOR.message_types_by_name['AdditionalPaymentDataNotify'] = _ADDITIONALPAYMENTDATANOTIFY

TrackNotify = _reflection.GeneratedProtocolMessageType('TrackNotify', (_message.Message,), dict(
  DESCRIPTOR = _TRACKNOTIFY,
  __module__ = 'CSNotify_pb2'
  # @@protoc_insertion_point(class_scope:pb.TrackNotify)
  ))
_sym_db.RegisterMessage(TrackNotify)

GameEventNotify = _reflection.GeneratedProtocolMessageType('GameEventNotify', (_message.Message,), dict(
  DESCRIPTOR = _GAMEEVENTNOTIFY,
  __module__ = 'CSNotify_pb2'
  # @@protoc_insertion_point(class_scope:pb.GameEventNotify)
  ))
_sym_db.RegisterMessage(GameEventNotify)

GameStatNotify = _reflection.GeneratedProtocolMessageType('GameStatNotify', (_message.Message,), dict(
  DESCRIPTOR = _GAMESTATNOTIFY,
  __module__ = 'CSNotify_pb2'
  # @@protoc_insertion_point(class_scope:pb.GameStatNotify)
  ))
_sym_db.RegisterMessage(GameStatNotify)

BroadcastNotify = _reflection.GeneratedProtocolMessageType('BroadcastNotify', (_message.Message,), dict(
  DESCRIPTOR = _BROADCASTNOTIFY,
  __module__ = 'CSNotify_pb2'
  # @@protoc_insertion_point(class_scope:pb.BroadcastNotify)
  ))
_sym_db.RegisterMessage(BroadcastNotify)

PlayerLevelUpNotify = _reflection.GeneratedProtocolMessageType('PlayerLevelUpNotify', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERLEVELUPNOTIFY,
  __module__ = 'CSNotify_pb2'
  # @@protoc_insertion_point(class_scope:pb.PlayerLevelUpNotify)
  ))
_sym_db.RegisterMessage(PlayerLevelUpNotify)

DailyFirstPayNotify = _reflection.GeneratedProtocolMessageType('DailyFirstPayNotify', (_message.Message,), dict(
  DESCRIPTOR = _DAILYFIRSTPAYNOTIFY,
  __module__ = 'CSNotify_pb2'
  # @@protoc_insertion_point(class_scope:pb.DailyFirstPayNotify)
  ))
_sym_db.RegisterMessage(DailyFirstPayNotify)

AdditionalPaymentDataNotify = _reflection.GeneratedProtocolMessageType('AdditionalPaymentDataNotify', (_message.Message,), dict(
  DESCRIPTOR = _ADDITIONALPAYMENTDATANOTIFY,
  __module__ = 'CSNotify_pb2'
  # @@protoc_insertion_point(class_scope:pb.AdditionalPaymentDataNotify)
  ))
_sym_db.RegisterMessage(AdditionalPaymentDataNotify)


# @@protoc_insertion_point(module_scope)
