# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CSPlatform.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import UserData_pb2
import Response_pb2
import Game_pb2
import CommonDef_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CSPlatform.proto',
  package='pb',
  serialized_pb=_b('\n\x10\x43SPlatform.proto\x12\x02pb\x1a\x0eUserData.proto\x1a\x0eResponse.proto\x1a\nGame.proto\x1a\x0f\x43ommonDef.proto\"\xed\x01\n\rLoginWorldReq\x12&\n\x0cUserBaseData\x18\x01 \x01(\x0b\x32\x10.pb.UserBaseData\x12\x0e\n\x06GameID\x18\x02 \x01(\r\x12\x11\n\tSceneType\x18\x03 \x01(\r\x12\x12\n\nSDKRawData\x18\x04 \x01(\t\x12\x13\n\x0bSDKSignData\x18\x05 \x01(\t\x12\x10\n\x08IsNative\x18\x06 \x01(\x08\x12\x38\n\x15\x41\x64\x64itionalChannelData\x18\x07 \x01(\x0b\x32\x19.pb.AdditionalChannelData\x12\x1c\n\x07\x41ppType\x18\x08 \x01(\x0e\x32\x0b.pb.AppType\"\xf7\x01\n\rLoginWorldRes\x12\x1c\n\x07ResBase\x18\x01 \x01(\x0b\x32\x0b.pb.ResBase\x12\x1e\n\x08UserData\x18\x02 \x01(\x0b\x32\x0c.pb.UserData\x12&\n\x0eGameServerList\x18\x03 \x03(\x0b\x32\x0e.pb.GameServer\x12\x34\n\x13GameOnlineStatsList\x18\x04 \x03(\x0b\x32\x13.pb.GameOnlineStatsB\x02\x18\x01\x12\x19\n\rCurrentGameID\x18\x05 \x01(\rB\x02\x18\x01\x12\x1f\n\x13\x43urrentGameServerID\x18\x06 \x01(\rB\x02\x18\x01\x12\x0e\n\x06\x43ookie\x18\x07 \x01(\t\"L\n\x0e\x42indAccountReq\x12\x13\n\x0b\x42indAccount\x18\x01 \x01(\t\x12\x15\n\rUnbindAccount\x18\x02 \x01(\t\x12\x0e\n\x06GameID\x18\x03 \x01(\r\".\n\x0e\x42indAccountRes\x12\x1c\n\x07ResBase\x18\x01 \x01(\x0b\x32\x0b.pb.ResBase\"T\n\x0cRedeemRecord\x12\x0c\n\x04Time\x18\x01 \x01(\r\x12\x12\n\nPropertyID\x18\x02 \x01(\r\x12\x0f\n\x07VIPCode\x18\x03 \x01(\t\x12\x11\n\tEBOrderID\x18\x04 \x01(\t\"\x15\n\x13GetRedeemHistoryReq\"[\n\x13GetRedeemHistoryRes\x12\x1c\n\x07ResBase\x18\x01 \x01(\x0b\x32\x0b.pb.ResBase\x12&\n\x0cRedeemRecord\x18\x02 \x03(\x0b\x32\x10.pb.RedeemRecord')
  ,
  dependencies=[UserData_pb2.DESCRIPTOR,Response_pb2.DESCRIPTOR,Game_pb2.DESCRIPTOR,CommonDef_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOGINWORLDREQ = _descriptor.Descriptor(
  name='LoginWorldReq',
  full_name='pb.LoginWorldReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserBaseData', full_name='pb.LoginWorldReq.UserBaseData', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameID', full_name='pb.LoginWorldReq.GameID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SceneType', full_name='pb.LoginWorldReq.SceneType', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SDKRawData', full_name='pb.LoginWorldReq.SDKRawData', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SDKSignData', full_name='pb.LoginWorldReq.SDKSignData', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IsNative', full_name='pb.LoginWorldReq.IsNative', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AdditionalChannelData', full_name='pb.LoginWorldReq.AdditionalChannelData', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AppType', full_name='pb.LoginWorldReq.AppType', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=323,
)


_LOGINWORLDRES = _descriptor.Descriptor(
  name='LoginWorldRes',
  full_name='pb.LoginWorldRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResBase', full_name='pb.LoginWorldRes.ResBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UserData', full_name='pb.LoginWorldRes.UserData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameServerList', full_name='pb.LoginWorldRes.GameServerList', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameOnlineStatsList', full_name='pb.LoginWorldRes.GameOnlineStatsList', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='CurrentGameID', full_name='pb.LoginWorldRes.CurrentGameID', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='CurrentGameServerID', full_name='pb.LoginWorldRes.CurrentGameServerID', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))),
    _descriptor.FieldDescriptor(
      name='Cookie', full_name='pb.LoginWorldRes.Cookie', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=573,
)


_BINDACCOUNTREQ = _descriptor.Descriptor(
  name='BindAccountReq',
  full_name='pb.BindAccountReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='BindAccount', full_name='pb.BindAccountReq.BindAccount', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UnbindAccount', full_name='pb.BindAccountReq.UnbindAccount', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameID', full_name='pb.BindAccountReq.GameID', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=575,
  serialized_end=651,
)


_BINDACCOUNTRES = _descriptor.Descriptor(
  name='BindAccountRes',
  full_name='pb.BindAccountRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResBase', full_name='pb.BindAccountRes.ResBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=653,
  serialized_end=699,
)


_REDEEMRECORD = _descriptor.Descriptor(
  name='RedeemRecord',
  full_name='pb.RedeemRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Time', full_name='pb.RedeemRecord.Time', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PropertyID', full_name='pb.RedeemRecord.PropertyID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='VIPCode', full_name='pb.RedeemRecord.VIPCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EBOrderID', full_name='pb.RedeemRecord.EBOrderID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=701,
  serialized_end=785,
)


_GETREDEEMHISTORYREQ = _descriptor.Descriptor(
  name='GetRedeemHistoryReq',
  full_name='pb.GetRedeemHistoryReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=787,
  serialized_end=808,
)


_GETREDEEMHISTORYRES = _descriptor.Descriptor(
  name='GetRedeemHistoryRes',
  full_name='pb.GetRedeemHistoryRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResBase', full_name='pb.GetRedeemHistoryRes.ResBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RedeemRecord', full_name='pb.GetRedeemHistoryRes.RedeemRecord', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=810,
  serialized_end=901,
)

_LOGINWORLDREQ.fields_by_name['UserBaseData'].message_type = UserData_pb2._USERBASEDATA
_LOGINWORLDREQ.fields_by_name['AdditionalChannelData'].message_type = UserData_pb2._ADDITIONALCHANNELDATA
_LOGINWORLDREQ.fields_by_name['AppType'].enum_type = CommonDef_pb2._APPTYPE
_LOGINWORLDRES.fields_by_name['ResBase'].message_type = Response_pb2._RESBASE
_LOGINWORLDRES.fields_by_name['UserData'].message_type = UserData_pb2._USERDATA
_LOGINWORLDRES.fields_by_name['GameServerList'].message_type = Game_pb2._GAMESERVER
_LOGINWORLDRES.fields_by_name['GameOnlineStatsList'].message_type = Game_pb2._GAMEONLINESTATS
_BINDACCOUNTRES.fields_by_name['ResBase'].message_type = Response_pb2._RESBASE
_GETREDEEMHISTORYRES.fields_by_name['ResBase'].message_type = Response_pb2._RESBASE
_GETREDEEMHISTORYRES.fields_by_name['RedeemRecord'].message_type = _REDEEMRECORD
DESCRIPTOR.message_types_by_name['LoginWorldReq'] = _LOGINWORLDREQ
DESCRIPTOR.message_types_by_name['LoginWorldRes'] = _LOGINWORLDRES
DESCRIPTOR.message_types_by_name['BindAccountReq'] = _BINDACCOUNTREQ
DESCRIPTOR.message_types_by_name['BindAccountRes'] = _BINDACCOUNTRES
DESCRIPTOR.message_types_by_name['RedeemRecord'] = _REDEEMRECORD
DESCRIPTOR.message_types_by_name['GetRedeemHistoryReq'] = _GETREDEEMHISTORYREQ
DESCRIPTOR.message_types_by_name['GetRedeemHistoryRes'] = _GETREDEEMHISTORYRES

LoginWorldReq = _reflection.GeneratedProtocolMessageType('LoginWorldReq', (_message.Message,), dict(
  DESCRIPTOR = _LOGINWORLDREQ,
  __module__ = 'CSPlatform_pb2'
  # @@protoc_insertion_point(class_scope:pb.LoginWorldReq)
  ))
_sym_db.RegisterMessage(LoginWorldReq)

LoginWorldRes = _reflection.GeneratedProtocolMessageType('LoginWorldRes', (_message.Message,), dict(
  DESCRIPTOR = _LOGINWORLDRES,
  __module__ = 'CSPlatform_pb2'
  # @@protoc_insertion_point(class_scope:pb.LoginWorldRes)
  ))
_sym_db.RegisterMessage(LoginWorldRes)

BindAccountReq = _reflection.GeneratedProtocolMessageType('BindAccountReq', (_message.Message,), dict(
  DESCRIPTOR = _BINDACCOUNTREQ,
  __module__ = 'CSPlatform_pb2'
  # @@protoc_insertion_point(class_scope:pb.BindAccountReq)
  ))
_sym_db.RegisterMessage(BindAccountReq)

BindAccountRes = _reflection.GeneratedProtocolMessageType('BindAccountRes', (_message.Message,), dict(
  DESCRIPTOR = _BINDACCOUNTRES,
  __module__ = 'CSPlatform_pb2'
  # @@protoc_insertion_point(class_scope:pb.BindAccountRes)
  ))
_sym_db.RegisterMessage(BindAccountRes)

RedeemRecord = _reflection.GeneratedProtocolMessageType('RedeemRecord', (_message.Message,), dict(
  DESCRIPTOR = _REDEEMRECORD,
  __module__ = 'CSPlatform_pb2'
  # @@protoc_insertion_point(class_scope:pb.RedeemRecord)
  ))
_sym_db.RegisterMessage(RedeemRecord)

GetRedeemHistoryReq = _reflection.GeneratedProtocolMessageType('GetRedeemHistoryReq', (_message.Message,), dict(
  DESCRIPTOR = _GETREDEEMHISTORYREQ,
  __module__ = 'CSPlatform_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetRedeemHistoryReq)
  ))
_sym_db.RegisterMessage(GetRedeemHistoryReq)

GetRedeemHistoryRes = _reflection.GeneratedProtocolMessageType('GetRedeemHistoryRes', (_message.Message,), dict(
  DESCRIPTOR = _GETREDEEMHISTORYRES,
  __module__ = 'CSPlatform_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetRedeemHistoryRes)
  ))
_sym_db.RegisterMessage(GetRedeemHistoryRes)


_LOGINWORLDRES.fields_by_name['GameOnlineStatsList'].has_options = True
_LOGINWORLDRES.fields_by_name['GameOnlineStatsList']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
_LOGINWORLDRES.fields_by_name['CurrentGameID'].has_options = True
_LOGINWORLDRES.fields_by_name['CurrentGameID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
_LOGINWORLDRES.fields_by_name['CurrentGameServerID'].has_options = True
_LOGINWORLDRES.fields_by_name['CurrentGameServerID']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\030\001'))
# @@protoc_insertion_point(module_scope)
