# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CSRank.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Response_pb2
import Common_pb2
import CSCommonDef_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CSRank.proto',
  package='pb',
  serialized_pb=_b('\n\x0c\x43SRank.proto\x12\x02pb\x1a\x0eResponse.proto\x1a\x0c\x43ommon.proto\x1a\x11\x43SCommonDef.proto\"H\n\x16GetPlatformRanklistReq\x12\x0e\n\x06UserID\x18\x01 \x01(\r\x12\x1e\n\x08RankType\x18\x02 \x01(\x0e\x32\x0c.pb.RankType\"}\n\x16GetPlatformRanklistRes\x12\x1c\n\x07ResBase\x18\x01 \x01(\x0b\x32\x0b.pb.ResBase\x12%\n\x0bTopRanklist\x18\x02 \x03(\x0b\x32\x10.pb.GameRankData\x12\x1e\n\x08RankType\x18\x03 \x01(\x0e\x32\x0c.pb.RankType\"Z\n\x12GetGameRanklistReq\x12\x0e\n\x06UserID\x18\x01 \x01(\r\x12\x1e\n\x08RankType\x18\x02 \x01(\x0e\x32\x0c.pb.RankType\x12\x14\n\x0cLastWeekFlag\x18\x03 \x01(\x08\"\xa1\x01\n\x12GetGameRanklistRes\x12\x1c\n\x07ResBase\x18\x01 \x01(\x0b\x32\x0b.pb.ResBase\x12%\n\x0bTopRanklist\x18\x02 \x03(\x0b\x32\x10.pb.GameRankData\x12\x1e\n\x08RankType\x18\x03 \x01(\x0e\x32\x0c.pb.RankType\x12\x14\n\x0cLastWeekFlag\x18\x04 \x01(\x08\x12\x10\n\x08SelfData\x18\x05 \x01(\x05\"Y\n\x16GetLastDayTopPlayerReq\x12\x0e\n\x06UserID\x18\x01 \x01(\r\x12\x1e\n\x08RankType\x18\x02 \x01(\x0e\x32\x0c.pb.RankType\x12\x0f\n\x07\x43urTime\x18\x03 \x01(\r\"\x98\x01\n\x16GetLastDayTopPlayerRes\x12\x1c\n\x07ResBase\x18\x01 \x01(\x0b\x32\x0b.pb.ResBase\x12\x1e\n\x08RankType\x18\x02 \x01(\x0e\x32\x0c.pb.RankType\x12\x13\n\x0bTopPlayerID\x18\x03 \x01(\r\x12\r\n\x05Value\x18\x04 \x01(\r\x12\x0c\n\x04Nick\x18\x05 \x01(\t\x12\x0e\n\x06RoleID\x18\x06 \x01(\r')
  ,
  dependencies=[Response_pb2.DESCRIPTOR,Common_pb2.DESCRIPTOR,CSCommonDef_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETPLATFORMRANKLISTREQ = _descriptor.Descriptor(
  name='GetPlatformRanklistReq',
  full_name='pb.GetPlatformRanklistReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserID', full_name='pb.GetPlatformRanklistReq.UserID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RankType', full_name='pb.GetPlatformRanklistReq.RankType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=141,
)


_GETPLATFORMRANKLISTRES = _descriptor.Descriptor(
  name='GetPlatformRanklistRes',
  full_name='pb.GetPlatformRanklistRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResBase', full_name='pb.GetPlatformRanklistRes.ResBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TopRanklist', full_name='pb.GetPlatformRanklistRes.TopRanklist', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RankType', full_name='pb.GetPlatformRanklistRes.RankType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=268,
)


_GETGAMERANKLISTREQ = _descriptor.Descriptor(
  name='GetGameRanklistReq',
  full_name='pb.GetGameRanklistReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserID', full_name='pb.GetGameRanklistReq.UserID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RankType', full_name='pb.GetGameRanklistReq.RankType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LastWeekFlag', full_name='pb.GetGameRanklistReq.LastWeekFlag', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=360,
)


_GETGAMERANKLISTRES = _descriptor.Descriptor(
  name='GetGameRanklistRes',
  full_name='pb.GetGameRanklistRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResBase', full_name='pb.GetGameRanklistRes.ResBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TopRanklist', full_name='pb.GetGameRanklistRes.TopRanklist', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RankType', full_name='pb.GetGameRanklistRes.RankType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='LastWeekFlag', full_name='pb.GetGameRanklistRes.LastWeekFlag', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SelfData', full_name='pb.GetGameRanklistRes.SelfData', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=363,
  serialized_end=524,
)


_GETLASTDAYTOPPLAYERREQ = _descriptor.Descriptor(
  name='GetLastDayTopPlayerReq',
  full_name='pb.GetLastDayTopPlayerReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UserID', full_name='pb.GetLastDayTopPlayerReq.UserID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RankType', full_name='pb.GetLastDayTopPlayerReq.RankType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CurTime', full_name='pb.GetLastDayTopPlayerReq.CurTime', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=615,
)


_GETLASTDAYTOPPLAYERRES = _descriptor.Descriptor(
  name='GetLastDayTopPlayerRes',
  full_name='pb.GetLastDayTopPlayerRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResBase', full_name='pb.GetLastDayTopPlayerRes.ResBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RankType', full_name='pb.GetLastDayTopPlayerRes.RankType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='TopPlayerID', full_name='pb.GetLastDayTopPlayerRes.TopPlayerID', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Value', full_name='pb.GetLastDayTopPlayerRes.Value', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Nick', full_name='pb.GetLastDayTopPlayerRes.Nick', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RoleID', full_name='pb.GetLastDayTopPlayerRes.RoleID', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=770,
)

_GETPLATFORMRANKLISTREQ.fields_by_name['RankType'].enum_type = CSCommonDef_pb2._RANKTYPE
_GETPLATFORMRANKLISTRES.fields_by_name['ResBase'].message_type = Response_pb2._RESBASE
_GETPLATFORMRANKLISTRES.fields_by_name['TopRanklist'].message_type = Common_pb2._GAMERANKDATA
_GETPLATFORMRANKLISTRES.fields_by_name['RankType'].enum_type = CSCommonDef_pb2._RANKTYPE
_GETGAMERANKLISTREQ.fields_by_name['RankType'].enum_type = CSCommonDef_pb2._RANKTYPE
_GETGAMERANKLISTRES.fields_by_name['ResBase'].message_type = Response_pb2._RESBASE
_GETGAMERANKLISTRES.fields_by_name['TopRanklist'].message_type = Common_pb2._GAMERANKDATA
_GETGAMERANKLISTRES.fields_by_name['RankType'].enum_type = CSCommonDef_pb2._RANKTYPE
_GETLASTDAYTOPPLAYERREQ.fields_by_name['RankType'].enum_type = CSCommonDef_pb2._RANKTYPE
_GETLASTDAYTOPPLAYERRES.fields_by_name['ResBase'].message_type = Response_pb2._RESBASE
_GETLASTDAYTOPPLAYERRES.fields_by_name['RankType'].enum_type = CSCommonDef_pb2._RANKTYPE
DESCRIPTOR.message_types_by_name['GetPlatformRanklistReq'] = _GETPLATFORMRANKLISTREQ
DESCRIPTOR.message_types_by_name['GetPlatformRanklistRes'] = _GETPLATFORMRANKLISTRES
DESCRIPTOR.message_types_by_name['GetGameRanklistReq'] = _GETGAMERANKLISTREQ
DESCRIPTOR.message_types_by_name['GetGameRanklistRes'] = _GETGAMERANKLISTRES
DESCRIPTOR.message_types_by_name['GetLastDayTopPlayerReq'] = _GETLASTDAYTOPPLAYERREQ
DESCRIPTOR.message_types_by_name['GetLastDayTopPlayerRes'] = _GETLASTDAYTOPPLAYERRES

GetPlatformRanklistReq = _reflection.GeneratedProtocolMessageType('GetPlatformRanklistReq', (_message.Message,), dict(
  DESCRIPTOR = _GETPLATFORMRANKLISTREQ,
  __module__ = 'CSRank_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetPlatformRanklistReq)
  ))
_sym_db.RegisterMessage(GetPlatformRanklistReq)

GetPlatformRanklistRes = _reflection.GeneratedProtocolMessageType('GetPlatformRanklistRes', (_message.Message,), dict(
  DESCRIPTOR = _GETPLATFORMRANKLISTRES,
  __module__ = 'CSRank_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetPlatformRanklistRes)
  ))
_sym_db.RegisterMessage(GetPlatformRanklistRes)

GetGameRanklistReq = _reflection.GeneratedProtocolMessageType('GetGameRanklistReq', (_message.Message,), dict(
  DESCRIPTOR = _GETGAMERANKLISTREQ,
  __module__ = 'CSRank_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetGameRanklistReq)
  ))
_sym_db.RegisterMessage(GetGameRanklistReq)

GetGameRanklistRes = _reflection.GeneratedProtocolMessageType('GetGameRanklistRes', (_message.Message,), dict(
  DESCRIPTOR = _GETGAMERANKLISTRES,
  __module__ = 'CSRank_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetGameRanklistRes)
  ))
_sym_db.RegisterMessage(GetGameRanklistRes)

GetLastDayTopPlayerReq = _reflection.GeneratedProtocolMessageType('GetLastDayTopPlayerReq', (_message.Message,), dict(
  DESCRIPTOR = _GETLASTDAYTOPPLAYERREQ,
  __module__ = 'CSRank_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetLastDayTopPlayerReq)
  ))
_sym_db.RegisterMessage(GetLastDayTopPlayerReq)

GetLastDayTopPlayerRes = _reflection.GeneratedProtocolMessageType('GetLastDayTopPlayerRes', (_message.Message,), dict(
  DESCRIPTOR = _GETLASTDAYTOPPLAYERRES,
  __module__ = 'CSRank_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetLastDayTopPlayerRes)
  ))
_sym_db.RegisterMessage(GetLastDayTopPlayerRes)


# @@protoc_insertion_point(module_scope)
