# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SSCommon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CSCommonDef_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SSCommon.proto',
  package='pb',
  serialized_pb=_b('\n\x0eSSCommon.proto\x12\x02pb\x1a\x11\x43SCommonDef.proto\"\xa7\x02\n\x13ManualBroadcastData\x12\x0e\n\x06Sender\x18\x01 \x01(\t\x12+\n\x05State\x18\x02 \x01(\x0e\x32\x1c.pb.BroadcastMsgSendStatType\x12\x13\n\x0bPlayedTimes\x18\x03 \x01(\r\x12\x13\n\x0b\x43hannelType\x18\x04 \x01(\r\x12\x0e\n\x06GameID\x18\x05 \x01(\r\x12\x13\n\x0b\x42roadcastID\x18\x06 \x01(\r\x12\x10\n\x08Priority\x18\x07 \x01(\r\x12\x11\n\tStartTime\x18\x08 \x01(\r\x12\x14\n\x0cSendInterval\x18\t \x01(\r\x12\x11\n\tSendTimes\x18\n \x01(\r\x12%\n\x07MsgType\x18\x0b \x01(\x0e\x32\x14.pb.BroadcastMsgType\x12\x0f\n\x07\x43ontent\x18\x0c \x01(\t\"\xbf\x01\n\x15GlobalDeliveryBagData\x12\x14\n\x0cPropertyType\x18\x01 \x01(\r\x12\x12\n\nPropertyID\x18\x02 \x01(\r\x12\x18\n\x10PropertyQuantity\x18\x03 \x01(\x03\x12\x16\n\x0e\x45xpirationTime\x18\x04 \x01(\r\x12\x16\n\x0e\x45xpirationDate\x18\x05 \x01(\t\x12\x15\n\rRefPropertyID\x18\x06 \x01(\r\x12\x1b\n\x13RefPropertyQuantity\x18\x07 \x01(\r')
  ,
  dependencies=[CSCommonDef_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MANUALBROADCASTDATA = _descriptor.Descriptor(
  name='ManualBroadcastData',
  full_name='pb.ManualBroadcastData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Sender', full_name='pb.ManualBroadcastData.Sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='State', full_name='pb.ManualBroadcastData.State', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PlayedTimes', full_name='pb.ManualBroadcastData.PlayedTimes', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChannelType', full_name='pb.ManualBroadcastData.ChannelType', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameID', full_name='pb.ManualBroadcastData.GameID', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BroadcastID', full_name='pb.ManualBroadcastData.BroadcastID', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Priority', full_name='pb.ManualBroadcastData.Priority', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='StartTime', full_name='pb.ManualBroadcastData.StartTime', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SendInterval', full_name='pb.ManualBroadcastData.SendInterval', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SendTimes', full_name='pb.ManualBroadcastData.SendTimes', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MsgType', full_name='pb.ManualBroadcastData.MsgType', index=10,
      number=11, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Content', full_name='pb.ManualBroadcastData.Content', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=337,
)


_GLOBALDELIVERYBAGDATA = _descriptor.Descriptor(
  name='GlobalDeliveryBagData',
  full_name='pb.GlobalDeliveryBagData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PropertyType', full_name='pb.GlobalDeliveryBagData.PropertyType', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PropertyID', full_name='pb.GlobalDeliveryBagData.PropertyID', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PropertyQuantity', full_name='pb.GlobalDeliveryBagData.PropertyQuantity', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ExpirationTime', full_name='pb.GlobalDeliveryBagData.ExpirationTime', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ExpirationDate', full_name='pb.GlobalDeliveryBagData.ExpirationDate', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RefPropertyID', full_name='pb.GlobalDeliveryBagData.RefPropertyID', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RefPropertyQuantity', full_name='pb.GlobalDeliveryBagData.RefPropertyQuantity', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=340,
  serialized_end=531,
)

_MANUALBROADCASTDATA.fields_by_name['State'].enum_type = CSCommonDef_pb2._BROADCASTMSGSENDSTATTYPE
_MANUALBROADCASTDATA.fields_by_name['MsgType'].enum_type = CSCommonDef_pb2._BROADCASTMSGTYPE
DESCRIPTOR.message_types_by_name['ManualBroadcastData'] = _MANUALBROADCASTDATA
DESCRIPTOR.message_types_by_name['GlobalDeliveryBagData'] = _GLOBALDELIVERYBAGDATA

ManualBroadcastData = _reflection.GeneratedProtocolMessageType('ManualBroadcastData', (_message.Message,), dict(
  DESCRIPTOR = _MANUALBROADCASTDATA,
  __module__ = 'SSCommon_pb2'
  # @@protoc_insertion_point(class_scope:pb.ManualBroadcastData)
  ))
_sym_db.RegisterMessage(ManualBroadcastData)

GlobalDeliveryBagData = _reflection.GeneratedProtocolMessageType('GlobalDeliveryBagData', (_message.Message,), dict(
  DESCRIPTOR = _GLOBALDELIVERYBAGDATA,
  __module__ = 'SSCommon_pb2'
  # @@protoc_insertion_point(class_scope:pb.GlobalDeliveryBagData)
  ))
_sym_db.RegisterMessage(GlobalDeliveryBagData)


# @@protoc_insertion_point(module_scope)
