# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SSMatch.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Match_pb2
import GameData_pb2
import Response_pb2
import CSCommonDef_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SSMatch.proto',
  package='pb',
  serialized_pb=_b('\n\rSSMatch.proto\x12\x02pb\x1a\x0bMatch.proto\x1a\x0eGameData.proto\x1a\x0eResponse.proto\x1a\x11\x43SCommonDef.proto\"\xd5\x02\n\x0eGlobalMatchReq\x12%\n\x06OpType\x18\x01 \x01(\x0e\x32\x15.pb.GlobalMatchOpType\x12\x18\n\x05Match\x18\x02 \x01(\x0b\x32\t.pb.Match\x12\x0e\n\x06GameID\x18\x03 \x01(\r\x12\x10\n\x08ServerID\x18\x04 \x01(\r\x12\x0e\n\x06UserID\x18\x05 \x01(\r\x12&\n\x0cMatchFeeType\x18\x06 \x01(\x0e\x32\x10.pb.MatchFeeType\x12\x15\n\rUserTotalRank\x18\x07 \x01(\r\x12\x31\n\x10PlayerMatchState\x18\x08 \x01(\x0e\x32\x17.pb.PlayerMatchStatType\x12\x34\n\x13MatchStatNotifyType\x18\t \x01(\x0e\x32\x17.pb.MatchStatNotifyType\x12(\n\x0bSignedMatch\x18\n \x01(\x0b\x32\x13.pb.PlayerMatchStat\".\n\x0eGlobalMatchRes\x12\x1c\n\x07ResBase\x18\x01 \x01(\x0b\x32\x0b.pb.ResBase*\xa2\x01\n\x11GlobalMatchOpType\x12\x14\n\x10GMOT_CLOSE_MATCH\x10\x01\x12\x1f\n\x1bGMOT_WEED_OUT_NOT_AVAILABLE\x10\x02\x12\x1a\n\x16GMOT_MATCH_STAT_NOTIFY\x10\x03\x12\x1c\n\x18GMOT_SIGNED_MATCH_UPDATE\x10\x04\x12\x1c\n\x18GMOT_SIGNED_MATCH_DELETE\x10\x05')
  ,
  dependencies=[Match_pb2.DESCRIPTOR,GameData_pb2.DESCRIPTOR,Response_pb2.DESCRIPTOR,CSCommonDef_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_GLOBALMATCHOPTYPE = _descriptor.EnumDescriptor(
  name='GlobalMatchOpType',
  full_name='pb.GlobalMatchOpType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GMOT_CLOSE_MATCH', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMOT_WEED_OUT_NOT_AVAILABLE', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMOT_MATCH_STAT_NOTIFY', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMOT_SIGNED_MATCH_UPDATE', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GMOT_SIGNED_MATCH_DELETE', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=478,
  serialized_end=640,
)
_sym_db.RegisterEnumDescriptor(_GLOBALMATCHOPTYPE)

GlobalMatchOpType = enum_type_wrapper.EnumTypeWrapper(_GLOBALMATCHOPTYPE)
GMOT_CLOSE_MATCH = 1
GMOT_WEED_OUT_NOT_AVAILABLE = 2
GMOT_MATCH_STAT_NOTIFY = 3
GMOT_SIGNED_MATCH_UPDATE = 4
GMOT_SIGNED_MATCH_DELETE = 5



_GLOBALMATCHREQ = _descriptor.Descriptor(
  name='GlobalMatchReq',
  full_name='pb.GlobalMatchReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='OpType', full_name='pb.GlobalMatchReq.OpType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Match', full_name='pb.GlobalMatchReq.Match', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GameID', full_name='pb.GlobalMatchReq.GameID', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ServerID', full_name='pb.GlobalMatchReq.ServerID', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UserID', full_name='pb.GlobalMatchReq.UserID', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MatchFeeType', full_name='pb.GlobalMatchReq.MatchFeeType', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UserTotalRank', full_name='pb.GlobalMatchReq.UserTotalRank', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PlayerMatchState', full_name='pb.GlobalMatchReq.PlayerMatchState', index=7,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MatchStatNotifyType', full_name='pb.GlobalMatchReq.MatchStatNotifyType', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SignedMatch', full_name='pb.GlobalMatchReq.SignedMatch', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=427,
)


_GLOBALMATCHRES = _descriptor.Descriptor(
  name='GlobalMatchRes',
  full_name='pb.GlobalMatchRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ResBase', full_name='pb.GlobalMatchRes.ResBase', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=475,
)

_GLOBALMATCHREQ.fields_by_name['OpType'].enum_type = _GLOBALMATCHOPTYPE
_GLOBALMATCHREQ.fields_by_name['Match'].message_type = Match_pb2._MATCH
_GLOBALMATCHREQ.fields_by_name['MatchFeeType'].enum_type = CSCommonDef_pb2._MATCHFEETYPE
_GLOBALMATCHREQ.fields_by_name['PlayerMatchState'].enum_type = CSCommonDef_pb2._PLAYERMATCHSTATTYPE
_GLOBALMATCHREQ.fields_by_name['MatchStatNotifyType'].enum_type = CSCommonDef_pb2._MATCHSTATNOTIFYTYPE
_GLOBALMATCHREQ.fields_by_name['SignedMatch'].message_type = GameData_pb2._PLAYERMATCHSTAT
_GLOBALMATCHRES.fields_by_name['ResBase'].message_type = Response_pb2._RESBASE
DESCRIPTOR.message_types_by_name['GlobalMatchReq'] = _GLOBALMATCHREQ
DESCRIPTOR.message_types_by_name['GlobalMatchRes'] = _GLOBALMATCHRES
DESCRIPTOR.enum_types_by_name['GlobalMatchOpType'] = _GLOBALMATCHOPTYPE

GlobalMatchReq = _reflection.GeneratedProtocolMessageType('GlobalMatchReq', (_message.Message,), dict(
  DESCRIPTOR = _GLOBALMATCHREQ,
  __module__ = 'SSMatch_pb2'
  # @@protoc_insertion_point(class_scope:pb.GlobalMatchReq)
  ))
_sym_db.RegisterMessage(GlobalMatchReq)

GlobalMatchRes = _reflection.GeneratedProtocolMessageType('GlobalMatchRes', (_message.Message,), dict(
  DESCRIPTOR = _GLOBALMATCHRES,
  __module__ = 'SSMatch_pb2'
  # @@protoc_insertion_point(class_scope:pb.GlobalMatchRes)
  ))
_sym_db.RegisterMessage(GlobalMatchRes)


# @@protoc_insertion_point(module_scope)
