# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CommonDef_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='UserData.proto',
  package='pb',
  serialized_pb=_b('\n\x0eUserData.proto\x12\x02pb\x1a\x0f\x43ommonDef.proto\"X\n\x0cUserBaseData\x12\x13\n\x0b\x43hannelType\x18\x01 \x01(\r\x12\x11\n\tChannelID\x18\x02 \x01(\t\x12\x10\n\x08Password\x18\x03 \x01(\t\x12\x0e\n\x06UserID\x18\x04 \x01(\r\"Z\n\rUserExtraData\x12\x0e\n\x06RoleID\x18\x01 \x01(\r\x12\x0c\n\x04Nick\x18\x02 \x01(\t\x12\x14\n\x03Sex\x18\x03 \x01(\x0e\x32\x07.pb.Sex\x12\x15\n\rBindChannelID\x18\x04 \x01(\t\"T\n\x08UserData\x12\"\n\x08\x42\x61seData\x18\x01 \x01(\x0b\x32\x10.pb.UserBaseData\x12$\n\tExtraData\x18\x02 \x01(\x0b\x32\x11.pb.UserExtraData\";\n\x15\x41\x64\x64itionalChannelData\x12\x0c\n\x04Nick\x18\x01 \x01(\t\x12\x14\n\x03Sex\x18\x02 \x01(\x0e\x32\x07.pb.Sex')
  ,
  dependencies=[CommonDef_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_USERBASEDATA = _descriptor.Descriptor(
  name='UserBaseData',
  full_name='pb.UserBaseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ChannelType', full_name='pb.UserBaseData.ChannelType', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ChannelID', full_name='pb.UserBaseData.ChannelID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Password', full_name='pb.UserBaseData.Password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='UserID', full_name='pb.UserBaseData.UserID', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=127,
)


_USEREXTRADATA = _descriptor.Descriptor(
  name='UserExtraData',
  full_name='pb.UserExtraData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='RoleID', full_name='pb.UserExtraData.RoleID', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Nick', full_name='pb.UserExtraData.Nick', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Sex', full_name='pb.UserExtraData.Sex', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='BindChannelID', full_name='pb.UserExtraData.BindChannelID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=219,
)


_USERDATA = _descriptor.Descriptor(
  name='UserData',
  full_name='pb.UserData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='BaseData', full_name='pb.UserData.BaseData', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ExtraData', full_name='pb.UserData.ExtraData', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=305,
)


_ADDITIONALCHANNELDATA = _descriptor.Descriptor(
  name='AdditionalChannelData',
  full_name='pb.AdditionalChannelData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Nick', full_name='pb.AdditionalChannelData.Nick', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Sex', full_name='pb.AdditionalChannelData.Sex', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=366,
)

_USEREXTRADATA.fields_by_name['Sex'].enum_type = CommonDef_pb2._SEX
_USERDATA.fields_by_name['BaseData'].message_type = _USERBASEDATA
_USERDATA.fields_by_name['ExtraData'].message_type = _USEREXTRADATA
_ADDITIONALCHANNELDATA.fields_by_name['Sex'].enum_type = CommonDef_pb2._SEX
DESCRIPTOR.message_types_by_name['UserBaseData'] = _USERBASEDATA
DESCRIPTOR.message_types_by_name['UserExtraData'] = _USEREXTRADATA
DESCRIPTOR.message_types_by_name['UserData'] = _USERDATA
DESCRIPTOR.message_types_by_name['AdditionalChannelData'] = _ADDITIONALCHANNELDATA

UserBaseData = _reflection.GeneratedProtocolMessageType('UserBaseData', (_message.Message,), dict(
  DESCRIPTOR = _USERBASEDATA,
  __module__ = 'UserData_pb2'
  # @@protoc_insertion_point(class_scope:pb.UserBaseData)
  ))
_sym_db.RegisterMessage(UserBaseData)

UserExtraData = _reflection.GeneratedProtocolMessageType('UserExtraData', (_message.Message,), dict(
  DESCRIPTOR = _USEREXTRADATA,
  __module__ = 'UserData_pb2'
  # @@protoc_insertion_point(class_scope:pb.UserExtraData)
  ))
_sym_db.RegisterMessage(UserExtraData)

UserData = _reflection.GeneratedProtocolMessageType('UserData', (_message.Message,), dict(
  DESCRIPTOR = _USERDATA,
  __module__ = 'UserData_pb2'
  # @@protoc_insertion_point(class_scope:pb.UserData)
  ))
_sym_db.RegisterMessage(UserData)

AdditionalChannelData = _reflection.GeneratedProtocolMessageType('AdditionalChannelData', (_message.Message,), dict(
  DESCRIPTOR = _ADDITIONALCHANNELDATA,
  __module__ = 'UserData_pb2'
  # @@protoc_insertion_point(class_scope:pb.AdditionalChannelData)
  ))
_sym_db.RegisterMessage(AdditionalChannelData)


# @@protoc_insertion_point(module_scope)
